import type { Question } from './types';

export const QUESTIONS_1_TO_3: Question[] = [
  {
    id: 'r1-q1', roomId: 1, lesson: 1, concept: 'Limit of a Function', title: 'The Chained Classroom Door',
    prompt: 'The glowing lock rejects direct substitution. Evaluate the limit to dissolve the chains.',
    latex: String.raw`\lim_{x\to2}\frac{x^2-4}{x-2}`,
    kind: 'number', expected: 4, tolerance: 0.0001,
    hint: 'Factor the numerator as a difference of squares, then cancel the common factor.',
    solutionTitle: 'Factor and cancel',
    solutionSteps: [
      String.raw`x^2-4=(x-2)(x+2)`,
      String.raw`\frac{(x-2)(x+2)}{x-2}=x+2\quad(x\ne2)`,
      String.raw`\lim_{x\to2}(x+2)=4`,
    ],
    explanation: 'The original expression is undefined at x = 2, but the nearby values follow x + 2, so the limit is 4.',
    environmentSuccess: 'The chains loosen and strike the floor.',
    environmentFailure: 'The lock pulses red. The Entity takes one step closer.',
  },
  {
    id: 'r1-q2', roomId: 1, lesson: 2, concept: 'One-Sided Limits', title: 'The Split Corridor',
    prompt: 'Only the left corridor is stable. Find the value approached from values less than 3.',
    latex: String.raw`f(x)=\begin{cases}2x+1,&x<3\\x^2-4,&x\ge3\end{cases}\qquad\lim_{x\to3^-}f(x)=?`,
    kind: 'choice', expected: 'b',
    options: [
      { id: 'a', label: '5', latex: '5' },
      { id: 'b', label: '7', latex: '7' },
      { id: 'c', label: '9', latex: '9' },
      { id: 'd', label: 'Does not exist', latex: String.raw`\text{DNE}` },
    ],
    hint: 'For a left-hand limit, use only the branch assigned to x < 3.',
    solutionTitle: 'Use the left branch',
    solutionSteps: [
      String.raw`x\to3^-\text{ means values just below }3`,
      String.raw`f(x)=2x+1\text{ on the left}`,
      String.raw`2(3)+1=7`,
    ],
    explanation: 'The left-hand limit uses the x < 3 formula, so the value approached is 7.',
    environmentSuccess: 'The false corridor folds into darkness while the correct passage holds.',
    environmentFailure: 'Both corridors twist. A whisper repeats: “Choose the correct side.”',
  },
  {
    id: 'r1-q3', roomId: 1, lesson: 3, concept: 'Infinite Limits', title: 'The Vertical Lock',
    prompt: 'A gauge rises without bound as the denominator approaches zero from the positive side.',
    latex: String.raw`\lim_{x\to2^+}\frac{1}{x-2}`,
    kind: 'choice', expected: 'a',
    options: [
      { id: 'a', label: 'Positive infinity', latex: String.raw`+\infty` },
      { id: 'b', label: 'Negative infinity', latex: String.raw`-\infty` },
      { id: 'c', label: '0', latex: '0' },
      { id: 'd', label: '2', latex: '2' },
    ],
    hint: 'Immediately to the right of 2, x − 2 is a very small positive number.',
    solutionTitle: 'Track the sign',
    solutionSteps: [
      String.raw`x\to2^+\Rightarrow x-2\to0^+`,
      String.raw`\frac{1}{\text{small positive}}\text{ grows without bound}`,
      String.raw`\lim_{x\to2^+}\frac1{x-2}=+\infty`,
    ],
    explanation: 'The denominator remains positive and approaches zero, so the quotient increases without bound.',
    environmentSuccess: 'The gauge breaks above its maximum mark. The first room releases you.',
    environmentFailure: 'The needle plunges through the glass and the hallway lights fail.',
  },
  {
    id: 'r2-q1', roomId: 2, lesson: 4, concept: 'Limits at Infinity', title: 'The Bridge Ratio',
    prompt: 'The bridge accepts only the long-run ratio of the leading terms.',
    latex: String.raw`\lim_{x\to\infty}\frac{5x^2-3x+1}{2x^2+7}`,
    kind: 'number', expected: 2.5, tolerance: 0.001,
    hint: 'The numerator and denominator have the same degree. Compare leading coefficients.',
    solutionTitle: 'Divide by the highest power',
    solutionSteps: [
      String.raw`\frac{5x^2-3x+1}{2x^2+7}=\frac{5-3/x+1/x^2}{2+7/x^2}`,
      String.raw`1/x\to0\text{ and }1/x^2\to0`,
      String.raw`\frac{5}{2}=2.5`,
    ],
    explanation: 'Equal-degree rational functions approach the ratio of their leading coefficients.',
    environmentSuccess: 'A missing bridge segment condenses from the fog.',
    environmentFailure: 'A plank tears free and disappears before it reaches the bottom.',
  },
  {
    id: 'r2-q2', roomId: 2, lesson: 5, concept: 'Exponential Limits', title: 'The Signal Lantern',
    prompt: 'The lantern needs the instantaneous growth factor of an exponential signal.',
    latex: String.raw`\lim_{x\to0}\frac{e^{2x}-1}{x}`,
    kind: 'number', expected: 2, tolerance: 0.001,
    hint: 'Let u = 2x and use the standard limit (eᵘ − 1)/u → 1.',
    solutionTitle: 'Rescale the standard limit',
    solutionSteps: [
      String.raw`u=2x\Rightarrow x=u/2`,
      String.raw`\frac{e^{2x}-1}{x}=2\frac{e^u-1}{u}`,
      String.raw`2\cdot1=2`,
    ],
    explanation: 'The standard exponential limit equals 1, and the inner factor 2 scales the result.',
    environmentSuccess: 'The lantern burns with a cold blue flame and reveals the next platform.',
    environmentFailure: 'The lantern exhales black smoke. Something moves beneath the bridge.',
  },
  {
    id: 'r2-q3', roomId: 2, lesson: 6, concept: 'Special Trigonometric Limits', title: 'The Stability Dial',
    prompt: 'Stabilize the final span using the fundamental sine limit.',
    latex: String.raw`\lim_{x\to0}\frac{\sin(5x)}{3x}`,
    kind: 'number', expected: 5 / 3, tolerance: 0.002,
    hint: 'Create sin(5x)/(5x), then multiply by the remaining constant.',
    solutionTitle: 'Create sin u over u',
    solutionSteps: [
      String.raw`\frac{\sin(5x)}{3x}=\frac53\cdot\frac{\sin(5x)}{5x}`,
      String.raw`\lim_{u\to0}\frac{\sin u}{u}=1`,
      String.raw`\frac53\cdot1=\frac53`,
    ],
    explanation: 'The fundamental sine limit is 1, leaving the scaling factor 5/3.',
    environmentSuccess: 'The bridge locks into place. The abyss finally has an opposite side.',
    environmentFailure: 'The dial slips. Fog pours upward like water running in reverse.',
  },
  {
    id: 'r3-q1', roomId: 3, lesson: 7, concept: 'Indeterminate Forms', title: 'The Unfinished Proof',
    prompt: 'The spirit’s work ends at 0/0. Resolve the indeterminate form.',
    latex: String.raw`\lim_{x\to1}\frac{x^2-1}{x-1}`,
    kind: 'number', expected: 2, tolerance: 0.0001,
    hint: '0/0 is not the final answer. Factor x² − 1.',
    solutionTitle: 'Resolve the indeterminate form',
    solutionSteps: [
      String.raw`\text{Direct substitution gives }0/0`,
      String.raw`x^2-1=(x-1)(x+1)`,
      String.raw`\lim_{x\to1}(x+1)=2`,
    ],
    explanation: 'An indeterminate form signals that algebraic simplification is required; the limit is 2.',
    environmentSuccess: 'The spirit’s erased final line rewrites itself in chalk.',
    environmentFailure: 'The page returns to 0/0 no matter how many times you blink.',
  },
  {
    id: 'r3-q2', roomId: 3, lesson: 8, concept: 'Continuous Functions', title: 'The Continuity Register',
    prompt: 'Choose the missing value that repairs the function at x = 3.',
    latex: String.raw`f(x)=\begin{cases}\dfrac{x^2-9}{x-3},&x\ne3\\k,&x=3\end{cases}\quad\text{Find }k.`,
    kind: 'number', expected: 6, tolerance: 0.0001,
    hint: 'Continuity requires f(3) to equal the limit as x approaches 3.',
    solutionTitle: 'Match the function value to the limit',
    solutionSteps: [
      String.raw`\frac{x^2-9}{x-3}=x+3\quad(x\ne3)`,
      String.raw`\lim_{x\to3}f(x)=6`,
      String.raw`k=f(3)=6`,
    ],
    explanation: 'Setting k = 6 makes the function value and two-sided limit agree.',
    environmentSuccess: 'A missing name returns to the attendance register.',
    environmentFailure: 'The register tears itself open at the same blank line.',
  },
  {
    id: 'r3-q3', roomId: 3, lesson: 9, concept: 'Discontinuous Functions', title: 'The Broken Record',
    prompt: 'Classify the discontinuity that repeats at x = 1.',
    latex: String.raw`f(x)=\frac{x^2-1}{x-1}\quad\text{at }x=1`,
    kind: 'choice', expected: 'a',
    options: [
      { id: 'a', label: 'Removable discontinuity (a hole)' },
      { id: 'b', label: 'Jump discontinuity' },
      { id: 'c', label: 'Infinite discontinuity' },
      { id: 'd', label: 'The function is continuous' },
    ],
    hint: 'The simplified expression approaches a finite value, but the original is undefined at x = 1.',
    solutionTitle: 'Identify the hole',
    solutionSteps: [
      String.raw`\frac{x^2-1}{x-1}=x+1\quad(x\ne1)`,
      String.raw`\lim_{x\to1}f(x)=2`,
      String.raw`f(1)\text{ is undefined, so the graph has a removable hole}`, 
    ],
    explanation: 'Defining f(1) = 2 would remove the discontinuity.',
    environmentSuccess: 'The record stops skipping. A spirit remembers her own name.',
    environmentFailure: 'The same second repeats: bell, scream, silence.',
  },
];
