import type { Question } from './types';

export const QUESTIONS_4_TO_5: Question[] = [
  {
    id: 'r4-q1', roomId: 4, lesson: 10, concept: 'Intermediate Value Theorem', title: 'The Shifting Corridor',
    prompt: 'The corridor changes sign between two doors. What does IVT guarantee?',
    latex: String.raw`f(x)=x^3-x-2,\qquad f(1)=-2,\quad f(2)=4`,
    kind: 'choice', expected: 'a',
    options: [
      { id: 'a', label: 'At least one c in (1, 2) satisfies f(c) = 0' },
      { id: 'b', label: 'Exactly one c in (1, 2) satisfies f(c) = 0' },
      { id: 'c', label: 'f has no zero in (1, 2)' },
      { id: 'd', label: 'The zero must be c = 1.5' },
    ],
    hint: 'A polynomial is continuous, and 0 lies between −2 and 4. IVT guarantees existence, not uniqueness.',
    solutionTitle: 'Apply the Intermediate Value Theorem',
    solutionSteps: [
      String.raw`f\text{ is a polynomial, so it is continuous on }[1,2]`,
      String.raw`f(1)=-2<0<4=f(2)`,
      String.raw`\exists c\in(1,2)\text{ such that }f(c)=0`,
    ],
    explanation: 'IVT guarantees at least one root in the interval, but not its exact value or uniqueness.',
    environmentSuccess: 'One shifting corridor becomes mathematically unavoidable.',
    environmentFailure: 'Every doorway relocates at once. The floor tilts toward the Entity.',
  },
  {
    id: 'r4-q2', roomId: 4, lesson: 11, concept: 'Average Rate of Change', title: 'The Motion Monitor',
    prompt: 'Calculate the average rate of change of the room’s position from t = 1 to t = 3.',
    latex: String.raw`s(t)=t^2+3t,\qquad\frac{s(3)-s(1)}{3-1}`,
    kind: 'number', expected: 7, tolerance: 0.0001,
    hint: 'Evaluate s(3) and s(1), then divide their difference by 2.',
    solutionTitle: 'Compute the secant slope',
    solutionSteps: [
      String.raw`s(3)=18`,
      String.raw`s(1)=4`,
      String.raw`\frac{18-4}{3-1}=7`,
    ],
    explanation: 'The average rate of change is the slope of the secant line: 7 units per time unit.',
    environmentSuccess: 'The monitor predicts the next movement before the walls can close.',
    environmentFailure: 'Your prediction arrives one second late. Metal scrapes behind you.',
  },
  {
    id: 'r4-q3', roomId: 4, lesson: 12, concept: 'Differentiation of Algebraic Functions', title: 'The Derivative Mechanism',
    prompt: 'The mechanism needs the instantaneous value f′(1).',
    latex: String.raw`f(x)=(x^2+1)(3x-2),\qquad f'(1)=?`,
    kind: 'number', expected: 8, tolerance: 0.0001,
    hint: 'Use the product rule: (uv)′ = u′v + uv′.',
    solutionTitle: 'Use the product rule',
    solutionSteps: [
      String.raw`u=x^2+1,\;u'=2x,\qquad v=3x-2,\;v'=3`,
      String.raw`f'(x)=2x(3x-2)+3(x^2+1)`,
      String.raw`f'(1)=2+6=8`,
    ],
    explanation: 'The product rule differentiates each factor while retaining the other factor in each term.',
    environmentSuccess: 'The mechanism turns before the room can rearrange itself again.',
    environmentFailure: 'The gears reverse and cut a doorway into the wrong wall.',
  },
  {
    id: 'r5-q1', roomId: 5, lesson: 2, concept: 'Two-Sided Limits', title: 'Final Desk I',
    prompt: 'The first exam seal opens only if both one-sided limits agree.',
    latex: String.raw`f(x)=\begin{cases}x+2,&x<1\\4-x,&x\ge1\end{cases}\qquad\lim_{x\to1}f(x)=?`,
    kind: 'number', expected: 3, tolerance: 0.0001,
    hint: 'Compute the left-hand and right-hand limits separately.',
    solutionTitle: 'Compare both sides',
    solutionSteps: [
      String.raw`\lim_{x\to1^-}(x+2)=3`,
      String.raw`\lim_{x\to1^+}(4-x)=3`,
      String.raw`\lim_{x\to1}f(x)=3`,
    ],
    explanation: 'The two-sided limit exists because both one-sided limits equal 3.',
    environmentSuccess: 'The first exam seal fades from the desk.',
    environmentFailure: 'The proctor’s red eyes open at the back of the hall.',
  },
  {
    id: 'r5-q2', roomId: 5, lesson: 4, concept: 'Limits at Infinity', title: 'Final Desk II',
    prompt: 'Determine the end behavior as the corridor extends toward negative infinity.',
    latex: String.raw`\lim_{x\to-\infty}\frac{4x^3-x}{-2x^3+5}`,
    kind: 'number', expected: -2, tolerance: 0.0001,
    hint: 'The degrees are equal. Compare the leading coefficients.',
    solutionTitle: 'Use the leading terms',
    solutionSteps: [
      String.raw`\text{Both polynomials have degree }3`,
      String.raw`\frac{4x^3}{-2x^3}\to\frac4{-2}`, 
      String.raw`\lim=-2`,
    ],
    explanation: 'The limit is the ratio of the leading coefficients, −2.',
    environmentSuccess: 'A second seal cracks. The hall grows shorter.',
    environmentFailure: 'The rows of desks multiply behind you.',
  },
  {
    id: 'r5-q3', roomId: 5, lesson: 8, concept: 'Continuity', title: 'Final Desk III',
    prompt: 'Judge the function at the marked point.',
    latex: String.raw`f(x)=\begin{cases}\dfrac{x^2-4}{x-2},&x\ne2\\6,&x=2\end{cases}`,
    kind: 'choice', expected: 'b',
    options: [
      { id: 'a', label: 'Continuous at x = 2' },
      { id: 'b', label: 'Not continuous: the limit is 4 but f(2) = 6' },
      { id: 'c', label: 'Not continuous: the limit does not exist' },
      { id: 'd', label: 'Not continuous: infinite discontinuity' },
    ],
    hint: 'Simplify the quotient and compare the limit at 2 with f(2).',
    solutionTitle: 'Check the continuity conditions',
    solutionSteps: [
      String.raw`\frac{x^2-4}{x-2}=x+2\quad(x\ne2)`,
      String.raw`\lim_{x\to2}f(x)=4`,
      String.raw`f(2)=6\ne4`,
    ],
    explanation: 'The function value does not equal the limit, so the function is not continuous at x = 2.',
    environmentSuccess: 'The third seal disappears. A spirit whispers your name beyond the exit.',
    environmentFailure: 'The answer sheet stains itself with a dark circle around 6.',
  },
  {
    id: 'r5-q4', roomId: 5, lesson: 10, concept: 'Intermediate Value Theorem', title: 'Final Desk IV',
    prompt: 'Select an interval where IVT guarantees a zero of g.',
    latex: String.raw`g(x)=x^2-5`,
    kind: 'choice', expected: 'c',
    options: [
      { id: 'a', label: '[0, 1]' },
      { id: 'b', label: '[1, 2]' },
      { id: 'c', label: '[2, 3]' },
      { id: 'd', label: '[3, 4]' },
    ],
    hint: 'Find endpoint values with opposite signs.',
    solutionTitle: 'Bracket the zero',
    solutionSteps: [
      String.raw`g(2)=-1`,
      String.raw`g(3)=4`,
      String.raw`g\text{ is continuous and changes sign on }[2,3]`,
    ],
    explanation: 'The interval [2, 3] contains a guaranteed zero because g changes sign and is continuous.',
    environmentSuccess: 'The fourth seal breaks. The Entity leaves the proctor’s desk.',
    environmentFailure: 'The Entity begins walking between the rows.',
  },
  {
    id: 'r5-q5', roomId: 5, lesson: 12, concept: 'Differentiation', title: 'Final Desk V',
    prompt: 'Complete the last derivative before the bell reaches zero.',
    latex: String.raw`f(x)=2x^3-5x^2+4x-7,\qquad f'(2)=?`,
    kind: 'number', expected: 8, tolerance: 0.0001,
    hint: 'Differentiate term by term with the power rule, then substitute x = 2.',
    solutionTitle: 'Apply the power rule',
    solutionSteps: [
      String.raw`f'(x)=6x^2-10x+4`,
      String.raw`f'(2)=6(4)-20+4`,
      String.raw`f'(2)=8`,
    ],
    explanation: 'Applying the power rule term by term gives f′(2) = 8.',
    environmentSuccess: 'The last seal shatters. The exit appears behind the Entity.',
    environmentFailure: 'The final bell loses another second. The Entity is almost within reach.',
  },
];
